# NAME: AYUSHI SINGH     
# SAP-ID: 60009220202  
# BATCH: D1-2

In [ ]:
pip install pandasql

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.1.4)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (2.0.32)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2024.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26772 sha256=ab9d00764fddfe9680665d9259813e8ef7ad8264d893105fb7c474b6b70b7f97
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandasql import sqldf

In [ ]:
df = pd.read_csv('/content/Air Quality.csv')

In [ ]:
df.isnull().sum()/len(df)

From Date          0.000000
To Date            0.000000
PM2.5 (ug/m3)      0.081606
PM10 (ug/m3)       0.079459
NO (ug/m3)         0.067574
NO2 (ug/m3)        0.068470
NOx (ppb)          0.064835
NH3 (ug/m3)        0.094438
SO2 (ug/m3)        0.082249
CO (mg/m3)         0.075689
Ozone (ug/m3)      0.077481
Benzene (ug/m3)    0.066560
Toluene (ug/m3)    0.066560
Temp (degree C)    0.068250
RH (%)             0.065410
WS (m/s)           0.065106
WD (deg)           0.075976
SR (W/mt2)         0.077109
BP (mmHg)          0.979696
VWS (m/s)          0.064396
Xylene (ug/m3)     0.066779
RF (mm)            0.065342
AT (degree C)      0.068690
dtype: float64

In [ ]:
df = df.dropna()

In [ ]:
df.duplicated().sum()

0

In [ ]:
df[['Date', 'Time']] = df['To Date'].str.split(' ', expand=True)

<ipython-input-8-500cf23cdcd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Date', 'Time']] = df['To Date'].str.split(' ', expand=True)
<ipython-input-8-500cf23cdcd2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Date', 'Time']] = df['To Date'].str.split(' ', expand=True)

In [ ]:
df = df.drop(columns=['From Date','BP (mmHg)'])

In [ ]:
df.columns

Index(['To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)', 'NO2 (ug/m3)',
       'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)', 'Date',
       'Time'],
      dtype='object')

In [ ]:
df.columns

Index(['To Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO (ug/m3)', 'NO2 (ug/m3)',
       'NOx (ppb)', 'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)',
       'Ozone (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Temp (degree C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'SR (W/mt2)',
       'VWS (m/s)', 'Xylene (ug/m3)', 'RF (mm)', 'AT (degree C)', 'Date',
       'Time'],
      dtype='object')

In [ ]:
df.head()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
5482,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
7405,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
21009,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
21158,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
22836,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00

# EXPLORING PANDAS SQL

In [ ]:
Query_string = """ select * from df limit 5 """
sqldf(Query_string, globals())

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
0,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
1,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
2,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
3,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
4,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00

# APPLY FILTER

In [ ]:
df[(df['Ozone (ug/m3)'] >= 10.5) & (df['Ozone (ug/m3)'] <=15.0)]

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
44182,2021-07-16 09:00:00,20.25,32.5,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.0,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
44233,2021-07-18 12:00:00,5.50,15.0,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.0,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
44419,2021-07-26 06:00:00,4.00,18.5,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.5,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
44422,2021-07-26 09:00:00,7.75,21.5,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.0,0.03,0.10,0.0,23.42,2021-07-26,09:00:00

In [ ]:
Query = """select * from df where `Ozone (ug/m3)` >= 10.5 and `Ozone (ug/m3)` <= 15.0"""
sqldf(Query,globals())

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
0,2021-07-16 09:00:00,20.25,32.5,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.0,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
1,2021-07-18 12:00:00,5.50,15.0,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.0,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
2,2021-07-26 06:00:00,4.00,18.5,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.5,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
3,2021-07-26 09:00:00,7.75,21.5,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.0,0.03,0.10,0.0,23.42,2021-07-26,09:00:00

# Distinct(Unique)

In [ ]:
df['NO (ug/m3)'].unique()

array([19.45,  1.27,  5.97, 28.62,  4.9 ,  2.08,  3.55,  3.95,  5.33,
       13.15,  3.08,  4.67,  4.33,  5.85, 18.95, 11.72,  3.25, 10.23,
        9.25])

In [ ]:
query_strin = """select distinct `NO (ug/m3)` from df;"""
sqldf(query_strin, globals())

    NO (ug/m3)
0        19.45
1         1.27
2         5.97
3        28.62
4         4.90
5         2.08
6         3.55
7         3.95
8         5.33
9        13.15
10        3.08
11        4.67
12        4.33
13        5.85
14       18.95
15       11.72
16        3.25
17       10.23
18        9.25

# IN

In [ ]:
df[df['Ozone (ug/m3)'].isin([15.00,12.20,10.60])]

Empty DataFrame
Columns: [To Date, PM2.5 (ug/m3), PM10 (ug/m3), NO (ug/m3), NO2 (ug/m3), NOx (ppb), NH3 (ug/m3), SO2 (ug/m3), CO (mg/m3), Ozone (ug/m3), Benzene (ug/m3), Toluene (ug/m3), Temp (degree C), RH (%), WS (m/s), WD (deg), SR (W/mt2), VWS (m/s), Xylene (ug/m3), RF (mm), AT (degree C), Date, Time]
Index: []

[0 rows x 23 columns]

In [ ]:
query_string = """
SELECT *
FROM df
WHERE "Ozone (ug/m3)" IN (15.00, 12.20, 10.60)
"""
sqldf(query_string, globals())

Empty DataFrame
Columns: [To Date, PM2.5 (ug/m3), PM10 (ug/m3), NO (ug/m3), NO2 (ug/m3), NOx (ppb), NH3 (ug/m3), SO2 (ug/m3), CO (mg/m3), Ozone (ug/m3), Benzene (ug/m3), Toluene (ug/m3), Temp (degree C), RH (%), WS (m/s), WD (deg), SR (W/mt2), VWS (m/s), Xylene (ug/m3), RF (mm), AT (degree C), Date, Time]
Index: []

[0 rows x 23 columns]

# NOT IN

In [ ]:
df[~df['Ozone (ug/m3)'].isin([15.00,12.20,10.60])]

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
5482,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
7405,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
21009,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
21158,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
22836,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00
33868,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
35140,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
44182,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
44192,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
44233,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
44245,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
44334,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
44419,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
44422,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
45387,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
50795,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
50797,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
50804,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
50805,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00

In [ ]:
query = """
SELECT *
FROM df
WHERE "Ozone (ug/m3)" NOT IN (15.00, 12.20, 10.60);
"""
sqldf(query,globals())

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
0,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
1,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
2,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
3,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
4,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00
5,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
6,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
7,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
8,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
9,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
10,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
11,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
12,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
13,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
14,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
15,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
16,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
17,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
18,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00

# ASCENDING DATA ORDER

In [ ]:
df.sort_values(by = ['PM2.5 (ug/m3)','PM10 (ug/m3)'] , ascending=True)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
44419,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
44245,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
44233,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
44422,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
44334,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
44192,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
33868,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
35140,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
45387,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
7405,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
44182,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
50797,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
5482,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
21158,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
21009,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
50804,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
50805,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00
50795,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
22836,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00

In [ ]:
query = """
SELECT *
FROM df
ORDER BY "PM2.5 (ug/m3)" ASC, "PM10 (ug/m3)" ASC
"""
sqldf(query,globals())

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
0,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00
1,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
2,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
3,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
4,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
5,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
6,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
7,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
8,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
9,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
10,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
11,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
12,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
13,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
14,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
15,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
16,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00
17,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
18,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00

# DESCENDING ORDER

In [ ]:
df.sort_values(by = ['PM2.5 (ug/m3)','PM10 (ug/m3)'] , ascending=False)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
22836,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00
50795,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
50805,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00
50804,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
21009,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
21158,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
5482,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
50797,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
44182,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
7405,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
45387,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
35140,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
33868,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
44192,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
44334,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
44422,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
44233,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
44245,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
44419,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00

In [ ]:
query = """
SELECT *
FROM df
ORDER BY "PM2.5 (ug/m3)" DESC, "PM10 (ug/m3)" DESC
"""
sqldf(query,globals())

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
0,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00
1,2022-04-17 22:00:00,63.75,116.00,11.72,40.23,30.92,9.68,20.15,1.12,19.45,...,84.33,0.30,274.50,34.25,-0.10,0.22,0.0,24.23,2022-04-17,22:00:00
2,2022-04-18 08:00:00,52.00,104.00,9.25,39.77,28.65,9.62,11.23,0.99,24.55,...,73.00,0.30,245.25,139.00,-0.10,0.12,0.0,25.23,2022-04-18,08:00:00
3,2022-04-18 07:00:00,52.00,97.75,10.23,44.50,31.98,9.47,8.80,1.06,17.55,...,79.50,0.70,215.00,50.75,-3.77,0.12,0.0,23.70,2022-04-18,07:00:00
4,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
5,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
6,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
7,2022-04-18 00:00:00,30.00,69.50,3.25,20.85,13.78,8.68,11.40,0.79,23.92,...,78.25,0.30,98.00,35.25,-0.10,0.20,0.0,24.30,2022-04-18,00:00:00
8,2021-07-16 09:00:00,20.25,32.50,3.95,9.60,8.32,7.23,4.28,0.76,11.32,...,83.00,0.30,67.00,188.00,-0.08,0.15,0.0,23.12,2021-07-16,09:00:00
9,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
10,2021-09-04 14:00:00,15.25,41.50,18.95,22.53,27.38,5.90,1.80,0.90,9.15,...,79.00,0.68,250.50,121.25,-0.10,0.30,0.0,24.22,2021-09-04,14:00:00
11,2020-07-04 15:00:00,11.50,33.50,3.55,8.68,7.50,3.08,4.97,0.58,26.90,...,66.75,0.97,127.00,26.50,0.08,0.10,0.0,24.25,2020-07-04,15:00:00
12,2020-05-12 15:00:00,11.25,33.25,2.08,6.20,4.97,3.00,0.10,0.28,50.78,...,58.50,1.17,171.25,87.75,-0.08,0.05,0.0,26.32,2020-05-12,15:00:00
13,2021-07-16 19:00:00,11.00,32.75,5.33,18.60,14.22,7.47,2.65,0.92,10.45,...,88.25,0.30,74.50,29.50,-0.10,0.23,0.0,22.90,2021-07-16,19:00:00
14,2021-07-22 17:00:00,10.50,24.75,4.67,11.42,9.88,5.72,2.62,0.65,19.17,...,82.50,0.28,64.00,40.50,0.00,0.50,0.0,24.15,2021-07-22,17:00:00
15,2021-07-26 09:00:00,7.75,21.50,5.85,13.90,12.17,5.12,7.25,0.66,13.90,...,78.00,0.82,148.33,244.00,0.03,0.10,0.0,23.42,2021-07-26,09:00:00
16,2021-07-18 12:00:00,5.50,15.00,13.15,25.25,24.15,7.15,6.70,0.71,13.55,...,79.33,0.35,150.00,333.00,0.05,0.20,0.0,24.23,2021-07-18,12:00:00
17,2021-07-19 00:00:00,5.00,12.50,3.08,8.85,7.20,6.12,1.10,0.58,20.90,...,79.00,0.30,83.50,12.25,0.00,0.10,0.0,22.60,2021-07-19,00:00:00
18,2021-07-26 06:00:00,4.00,18.50,4.33,8.68,8.12,5.90,3.62,0.59,14.80,...,81.50,0.30,183.50,77.50,0.05,0.08,0.0,22.45,2021-07-26,06:00:00

# AGGREGATION

In [ ]:
df.agg( {'CO (mg/m3)': ['count','min','max','mean'] })

       CO (mg/m3)
count   19.000000
min      0.220000
max      1.120000
mean     0.702105

In [ ]:
query = """
SELECT
    COUNT("CO (mg/m3)") AS count,
    MIN("CO (mg/m3)") AS min,
    MAX("CO (mg/m3)") AS max,
    AVG("CO (mg/m3)") AS mean
FROM df;
"""
sqldf(query, globals())

   count   min   max      mean
0     19  0.22  1.12  0.702105

# GROUP BY

In [ ]:
df.groupby('SO2 (ug/m3)')['RH (%)'].sum()

SO2 (ug/m3)
0.10      58.50
1.10      79.00
1.80      79.00
2.62     169.50
2.65      88.25
3.62      81.50
3.73      80.75
4.28      83.00
4.47      88.50
4.65      88.67
4.97      66.75
5.13      75.00
6.70      79.33
7.25      78.00
8.80      79.50
11.23     73.00
11.40     78.25
20.15     84.33
Name: RH (%), dtype: float64

In [ ]:
query = """
SELECT
    "SO2 (ug/m3)",
    SUM("RH (%)") AS sum_rh
FROM df
GROUP BY "SO2 (ug/m3)";
"""
sqldf(query, globals())

    SO2 (ug/m3)  sum_rh
0          0.10   58.50
1          1.10   79.00
2          1.80   79.00
3          2.62  169.50
4          2.65   88.25
5          3.62   81.50
6          3.73   80.75
7          4.28   83.00
8          4.47   88.50
9          4.65   88.67
10         4.97   66.75
11         5.13   75.00
12         6.70   79.33
13         7.25   78.00
14         8.80   79.50
15        11.23   73.00
16        11.40   78.25
17        20.15   84.33

## Group by  with Aggregration

In [ ]:
df.groupby('WD (deg)').agg( {'SR (W/mt2)': ['mean','min','max'] })

         SR (W/mt2)
               mean     min     max
WD (deg)
38.00          3.00    3.00    3.00
64.00         40.50   40.50   40.50
67.00        188.00  188.00  188.00
74.50         29.50   29.50   29.50
83.50         12.25   12.25   12.25
98.00         35.25   35.25   35.25
102.67         7.00    7.00    7.00
119.25         3.00    3.00    3.00
127.00        26.50   26.50   26.50
148.33       244.00  244.00  244.00
150.00       333.00  333.00  333.00
171.25        87.75   87.75   87.75
181.00         2.00    2.00    2.00
183.50        77.50   77.50   77.50
215.00        50.75   50.75   50.75
245.25       139.00  139.00  139.00
250.50       121.25  121.25  121.25
274.50        34.25   34.25   34.25
290.00         6.75    6.75    6.75

In [ ]:
query = """
SELECT
    "WD (deg)",
    AVG("SR (W/mt2)") AS avg_sr,
    MIN("SR (W/mt2)") AS min_sr,
    MAX("SR (W/mt2)") AS max_sr
FROM df
GROUP BY "WD (deg)";
"""
sqldf(query,globals())

    WD (deg)  avg_sr  min_sr  max_sr
0      38.00    3.00    3.00    3.00
1      64.00   40.50   40.50   40.50
2      67.00  188.00  188.00  188.00
3      74.50   29.50   29.50   29.50
4      83.50   12.25   12.25   12.25
5      98.00   35.25   35.25   35.25
6     102.67    7.00    7.00    7.00
7     119.25    3.00    3.00    3.00
8     127.00   26.50   26.50   26.50
9     148.33  244.00  244.00  244.00
10    150.00  333.00  333.00  333.00
11    171.25   87.75   87.75   87.75
12    181.00    2.00    2.00    2.00
13    183.50   77.50   77.50   77.50
14    215.00   50.75   50.75   50.75
15    245.25  139.00  139.00  139.00
16    250.50  121.25  121.25  121.25
17    274.50   34.25   34.25   34.25
18    290.00    6.75    6.75    6.75

# JOIN (MERGE)

In [ ]:
data1 = {
        'Empid': [1011, 1012, 1013, 1014, 1015],
        'Name': ['John', 'Rahul', 'Rick', 'Morty', 'Tim'],
        'Designation': ['Manager', 'Research Engineer', ' Research Engineer', 'VP', 'Delivery Manager'],
        'Date_of_joining': ['01-Jan-2000', '23-sep-2006', '11-Jan-2012', '21-Jan-1991', '12-Jan-1990']}
Emp_df = pd.DataFrame(data1, columns = ['Empid', 'Name', 'Designation','Date_of_joining'])
Emp_df

   Empid   Name         Designation Date_of_joining
0   1011   John             Manager     01-Jan-2000
1   1012  Rahul   Research Engineer     23-sep-2006
2   1013   Rick   Research Engineer     11-Jan-2012
3   1014  Morty                  VP     21-Jan-1991
4   1015    Tim    Delivery Manager     12-Jan-1990

In [ ]:
data2 = {
        'Empid': [1011, 1017, 1013, 1019, 1015],
        'Deptartment': ['Management', 'Research', 'Research', 'Management', 'Delivery'],
        'Total_Experience': [18, 10, 10, 28, 22]}
Dept_df = pd.DataFrame(data2, columns = ['Empid', 'Deptartment', 'Total_Experience'])
Dept_df

   Empid Deptartment  Total_Experience
0   1011  Management                18
1   1017    Research                10
2   1013    Research                10
3   1019  Management                28
4   1015    Delivery                22

#INNER JOIN

In [ ]:
pd.merge(Emp_df,Dept_df,left_on='Empid',right_on='Empid',how='inner')

,Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,Management,18
1,1013,Rick,Research Engineer,11-Jan-2012,Research,10
2,1015,Tim,Delivery Manager,12-Jan-1990,Delivery,22

In [ ]:
query = """
SELECT * FROM Emp_df a
 INNER JOIN Dept_df b
 On a.Empid = b.Empid;
 """
sqldf(query,globals())

,Empid,Name,Designation,Date_of_joining,Empid,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,1011,Management,18
1,1013,Rick,Research Engineer,11-Jan-2012,1013,Research,10
2,1015,Tim,Delivery Manager,12-Jan-1990,1015,Delivery,22

# LEFT JOIN

In [ ]:
pd.merge(Emp_df,Dept_df,left_on='Empid',right_on='Empid',how='left')

,Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,Management,18.0
1,1012,Rahul,Research Engineer,23-sep-2006,NaN,NaN
2,1013,Rick,Research Engineer,11-Jan-2012,Research,10.0
3,1014,Morty,VP,21-Jan-1991,NaN,NaN
4,1015,Tim,Delivery Manager,12-Jan-1990,Delivery,22.0

In [ ]:
query = """
SELECT * FROM Emp_df a
 LEFT JOIN Dept_df b
 On a.Empid = b.Empid;
 """
sqldf(query,globals())

,Empid,Name,Designation,Date_of_joining,Empid,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,1011.0,Management,18.0
1,1012,Rahul,Research Engineer,23-sep-2006,NaN,None,NaN
2,1013,Rick,Research Engineer,11-Jan-2012,1013.0,Research,10.0
3,1014,Morty,VP,21-Jan-1991,NaN,None,NaN
4,1015,Tim,Delivery Manager,12-Jan-1990,1015.0,Delivery,22.0

# RIGHT JOIN

In [ ]:
pd.merge(Emp_df,Dept_df,left_on='Empid',right_on='Empid',how='right')

,Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,Management,18
1,1017,NaN,NaN,NaN,Research,10
2,1013,Rick,Research Engineer,11-Jan-2012,Research,10
3,1019,NaN,NaN,NaN,Management,28
4,1015,Tim,Delivery Manager,12-Jan-1990,Delivery,22

In [ ]:
query = """
select a.Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience from Dept_df a LEFT JOIN Emp_df b ON  a.Empid = b.Empid;
 """
sqldf(query,globals())

,Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,Management,18
1,1017,None,None,None,Research,10
2,1013,Rick,Research Engineer,11-Jan-2012,Research,10
3,1019,None,None,None,Management,28
4,1015,Tim,Delivery Manager,12-Jan-1990,Delivery,22

#OUTER JOIN

In [ ]:
pd.merge(Emp_df,Dept_df,left_on='Empid',right_on='Empid',how='outer')

,Empid,Name,Designation,Date_of_joining,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,Management,18.0
1,1012,Rahul,Research Engineer,23-sep-2006,NaN,NaN
2,1013,Rick,Research Engineer,11-Jan-2012,Research,10.0
3,1014,Morty,VP,21-Jan-1991,NaN,NaN
4,1015,Tim,Delivery Manager,12-Jan-1990,Delivery,22.0
5,1017,NaN,NaN,NaN,Research,10.0
6,1019,NaN,NaN,NaN,Management,28.0

In [ ]:
query = """select * from Emp_df a left OUTER JOIN Dept_df b ON  a.Empid = b.Empid;
 """
sqldf(query,globals())

,Empid,Name,Designation,Date_of_joining,Empid,Deptartment,Total_Experience
0,1011,John,Manager,01-Jan-2000,1011.0,Management,18.0
1,1012,Rahul,Research Engineer,23-sep-2006,NaN,None,NaN
2,1013,Rick,Research Engineer,11-Jan-2012,1013.0,Research,10.0
3,1014,Morty,VP,21-Jan-1991,NaN,None,NaN
4,1015,Tim,Delivery Manager,12-Jan-1990,1015.0,Delivery,22.0

# SUMMARY

In [ ]:
df.describe()

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),Toluene (ug/m3),Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.0,19.000000
mean,26.723684,53.552632,8.400000,27.928421,21.687368,9.337368,5.645789,0.702105,29.483158,0.728421,1.559474,31.453158,79.517368,0.757368,151.750000,75.855263,-0.230526,0.214737,0.0,22.761579
std,21.174194,33.489486,7.201076,22.139105,16.280906,6.222046,4.681715,0.242340,26.678429,0.669430,1.086725,5.592556,7.521971,0.597493,76.138641,92.087531,0.859266,0.218667,0.0,2.475325
min,4.000000,12.500000,1.270000,6.200000,4.970000,3.000000,0.100000,0.220000,9.150000,0.000000,0.300000,27.220000,58.500000,0.280000,38.000000,2.000000,-3.770000,0.000000,0.0,17.500000
25%,10.750000,28.625000,3.750000,10.510000,9.100000,5.900000,2.635000,0.580000,14.350000,0.325000,0.750000,28.810000,78.125000,0.300000,90.750000,9.625000,-0.100000,0.100000,0.0,22.525000
50%,16.000000,41.500000,5.330000,22.530000,15.570000,7.230000,4.470000,0.670000,19.270000,0.530000,1.200000,29.800000,79.500000,0.680000,148.330000,35.250000,-0.030000,0.180000,0.0,23.600000
75%,42.625000,68.875000,10.975000,40.000000,28.015000,9.650000,6.975000,0.885000,25.725000,0.775000,2.235000,30.665000,83.665000,1.020000,199.250000,104.500000,0.000000,0.225000,0.0,24.230000
max,67.500000,116.000000,28.620000,97.280000,67.550000,24.850000,20.150000,1.120000,111.550000,2.830000,4.400000,47.120000,88.670000,2.320000,290.000000,333.000000,0.080000,1.000000,0.0,26.320000

# RESAMPLING

In [ ]:
resam = pd.read_csv('/content/Air Quality.csv',index_col = 0,parse_dates = ['To Date'])
df.head()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,RH (%),WS (m/s),WD (deg),SR (W/mt2),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),Date,Time
5482,2017-02-14 21:00:00,39.25,65.50,19.45,97.28,67.55,9.75,3.73,0.47,16.15,...,80.75,2.03,290.00,6.75,-0.03,1.00,0.0,18.40,2017-02-14,21:00:00
7405,2017-05-06 00:00:00,16.00,56.00,1.27,27.27,15.57,7.00,5.13,0.22,19.27,...,75.00,1.07,102.67,7.00,0.00,0.00,0.0,23.60,2017-05-06,00:00:00
21009,2018-11-23 20:00:00,45.50,68.25,5.97,31.43,21.57,24.85,4.65,0.67,111.55,...,88.67,2.32,119.25,3.00,-0.10,0.23,0.0,18.65,2018-11-23,20:00:00
21158,2018-11-30 01:00:00,39.75,67.50,28.62,54.45,52.23,24.62,4.47,0.87,70.30,...,88.50,1.18,38.00,3.00,-0.03,0.20,0.0,17.50,2018-11-30,01:00:00
22836,2019-02-07 23:00:00,67.50,107.25,4.90,41.15,25.90,17.05,2.62,0.52,66.52,...,87.00,0.72,181.00,2.00,0.00,0.18,0.0,19.20,2019-02-07,23:00:00

# RESAMPLING BY MONTH

In [ ]:
resam.set_index('To Date', inplace=True)

In [ ]:
resam[['SR (W/mt2)']].resample('M').mean()

            SR (W/mt2)
To Date
2016-07-31  115.709217
2016-08-31  119.050999
2016-09-30   98.144458
2016-10-31  111.994538
2016-11-30  106.467077
...                ...
2022-12-31   61.846438
2023-01-31   90.558704
2023-02-28  110.898185
2023-03-31  104.868775
2023-04-30   11.000000

[82 rows x 1 columns]

#RESAMPLING BY QUARTER

In [ ]:
resam[['SR (W/mt2)']].resample('Q').mean()

            SR (W/mt2)
To Date
2016-09-30  111.703911
2016-12-31  103.296326
2017-03-31  112.906214
2017-06-30  124.580167
2017-09-30   48.371930
2017-12-31   37.941268
2018-03-31   68.343139
2018-06-30   70.590845
2018-09-30   45.870817
2018-12-31   42.117576
2019-03-31   59.970142
2019-06-30  103.180896
2019-09-30   42.025644
2019-12-31   29.507897
2020-03-31   58.357504
2020-06-30   69.354565
2020-09-30   40.291876
2020-12-31   32.715207
2021-03-31   59.570607
2021-06-30  100.131109
2021-09-30   96.566809
2021-12-31   63.468011
2022-03-31   97.530362
2022-06-30  113.179686
2022-09-30   86.301921
2022-12-31   67.084284
2023-03-31  101.829814
2023-06-30   11.000000

#RESAMPLING BY YEAR

In [ ]:
resam[ ['SR (W/mt2)'] ].resample('Y').mean()

            SR (W/mt2)
To Date
2016-12-31  107.376942
2017-12-31   82.454701
2018-12-31   56.243142
2019-12-31   54.359797
2020-12-31   50.018232
2021-12-31   79.105751
2022-12-31   91.070607
2023-12-31  101.787705

#RESAMPLING BY WEEK

In [ ]:
resam[ ['SR (W/mt2)'] ].resample('w').mean()

            SR (W/mt2)
To Date
2016-07-03  116.245200
2016-07-10   97.097205
2016-07-17  140.827152
2016-07-24   95.648557
2016-07-31  120.749477
...                ...
2023-03-05  114.050595
2023-03-12  112.974702
2023-03-19   90.955090
2023-03-26  100.747024
2023-04-02  108.838843

[353 rows x 1 columns]

# Resampling on a Semimonthly Basis

In [ ]:
resam[ ['SR (W/mt2)'] ].resample('SM').mean()

            SR (W/mt2)
To Date
2016-06-30  114.232984
2016-07-15  120.251953
2016-07-31  116.787615
2016-08-15  122.133750
2016-08-31   89.496923
...                ...
2023-01-31  105.626611
2023-02-15  114.649840
2023-02-28  113.967361
2023-03-15   96.708225
2023-03-31  104.810000

[163 rows x 1 columns]

#WINDOWING FUNCTION

In [ ]:
win = pd.read_csv('/content/Air Quality.csv',index_col=0, parse_dates=['To Date'])
win.head()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,14.5,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,10.5,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

# ROLLING WINDOW

In [ ]:
win_cleaned = win.drop(columns=['To Date'])

In [ ]:
win_cleaned.rolling(window=4).mean().head(10)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 17:00:00,14.7925,56.7500,21.3825,46.0375,38.3800,7.0125,6.2100,0.470,13.6275,0.7175,...,33.5425,63.8125,1.6825,216.9175,130.1050,NaN,-0.1,0.1325,0.0,NaN
2016-07-01 18:00:00,14.1675,58.6875,21.1575,46.1875,38.2675,7.3700,6.1325,0.465,14.0525,0.7425,...,33.4575,63.8750,1.7500,216.3550,73.4800,NaN,-0.1,0.1325,0.0,25.3375
2016-07-01 19:00:00,13.3550,59.5625,17.6900,45.1575,35.1950,7.7400,6.0500,0.440,16.7775,0.7250,...,33.3875,63.9375,2.0000,218.2100,37.1675,NaN,-0.1,0.1325,0.0,25.1050

#EXPANDING WINDOW

In [ ]:
win_cleaned.expanding(min_periods=4).mean().head(10)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 11:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 15:00:00,12.105000,46.875000,19.467500,42.455000,35.257500,6.867500,NaN,0.487500,11.650000,0.767500,...,33.562500,67.230000,2.020000,221.395000,175.605000,NaN,-0.1,0.100000,0.0,NaN
2016-07-01 16:00:00,12.018000,49.500000,20.920000,43.784000,36.966000,6.880000,6.302500,0.482000,12.806000,0.774000,...,33.564000,66.584000,1.916000,218.850000,159.018000,NaN,-0.1,0.126000,0.0,NaN
2016-07-01 17:00:00,11.973333,50.833333,20.616667,44.208333,36.941667,7.086667,6.288000,0.475000,14.001667,0.761667,...,33.550000,66.153333,1.921667,219.500000,138.348333,NaN,-0.1,0.121667,0.0,24.875
2016-07-01 18:00:00,12.834286,51.821429,19.742857,44.207143,36.282857,7.185714,6.251667,0.471429,13.744286,0.752857,...,33.504286,65.810000,1.954286,219.678571,120.584286,NaN,-0.1,0.118571,0.0,24.880
2016-07-01 19:00:00,12.730000,53.218750,18.578750,43.806250,35.226250,7.303750,6.244286,0.463750,14.213750,0.746250,...,33.475000,65.583750,2.010000,219.802500,106.386250,NaN,-0.1,0.116250,0.0,24.845

# Exponentially Weighted Moving Window

In [ ]:
win_cleaned.ewm(com=0.5).mean().head(10)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,10.670000,39.000000,17.670000,39.200000,32.330000,7.070000,6.600000,0.480000,14.500000,1.000000,...,33.430000,71.670000,2.300000,226.330000,123.670000,NaN,-0.1,0.100000,0.0,23.050000
2016-07-01 11:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.417500,NaN,-0.1,0.100000,0.0,23.050000
2016-07-01 12:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.417500,NaN,-0.1,0.100000,0.0,23.050000
2016-07-01 13:00:00,4.167500,39.000000,19.792500,41.225000,34.932500,7.317500,6.600000,0.487500,14.875000,0.775000,...,33.632500,70.417500,2.450000,223.832500,170.417500,NaN,-0.1,0.100000,0.0,23.050000
2016-07-01 14:00:00,19.731412,49.482353,15.606706,43.488235,32.881294,6.395529,6.382683,0.470824,10.705882,0.608235,...,33.572941,63.825529,1.906824,223.039176,237.202000,NaN,-0.1,0.100000,0.0,23.050000
2016-07-01 15:00:00,16.411341,56.903963,22.047165,44.697134,38.244116,6.584055,6.492831,0.499848,7.664024,0.728079,...,33.555945,63.769573,1.531341,215.786829,174.265000,NaN,-0.1,0.100000,0.0,25.589549
2016-07-01 16:00:00,13.141296,59.039262,25.276859,47.733737,42.075941,6.822649,5.944469,0.472365,14.399499,0.777682,...,33.565639,63.928496,1.509726,210.878439,117.989924,NaN,-0.1,0.189659,0.0,25.672302
2016-07-01 17:00:00,12.203329,58.001541,21.112620,46.787383,38.532555,7.697281,6.137143,0.450546,18.161692,0.725311,...,33.507904,63.976702,1.806544,218.881862,62.040798,NaN,-0.1,0.129214,0.0,25.310823
2016-07-01 18:00:00,16.082162,57.833223,16.687796,45.056040,34.382125,7.752632,6.092201,0.450181,14.172435,0.708374,...,33.321945,63.825005,2.036367,220.131924,29.894375,NaN,-0.1,0.109665,0.0,25.033546
2016-07-01 19:00:00,13.357352,61.282005,12.510768,42.348666,30.008635,8.004522,6.164163,0.423360,16.393558,0.702785,...,33.287272,63.941813,2.279089,220.491085,14.612566,NaN,-0.1,0.103214,0.0,24.790189

#SHIFTING

In [ ]:
shifting = pd.read_csv('/content/Air Quality.csv',index_col=0,parse_dates=['To Date'])
shifting.head()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,14.5,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,10.5,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

In [ ]:
shifting.shift(periods=3).head(7)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 11:00:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.6,0.48,14.5,...,33.43,71.67,2.3,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 14:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,...,33.70,70.00,2.5,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 15:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 16:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
shifting.shift(periods=-1).head(7)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.90,35.80,7.40,NaN,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.10,0.0,NaN
2016-07-01 11:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 12:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.10,0.0,NaN
2016-07-01 14:00:00,2016-07-01 16:00:00,15.25,59.5,24.30,45.12,40.12,6.65,6.53,0.51,6.60,...,33.55,63.75,1.40,213.25,152.25,NaN,-0.1,0.10,0.0,25.60
2016-07-01 15:00:00,2016-07-01 17:00:00,11.67,60.0,26.73,49.10,43.80,6.93,5.70,0.46,17.43,...,33.57,64.00,1.50,208.67,92.67,NaN,-0.1,0.23,0.0,25.70
2016-07-01 16:00:00,2016-07-01 18:00:00,11.75,57.5,19.10,46.33,36.82,8.12,6.23,0.44,19.98,...,33.48,64.00,1.95,222.75,35.00,NaN,-0.1,0.10,0.0,25.15

In [ ]:
shifting.shift(periods=3, axis=1).head(7)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,NaT,NaT,NaT,2016-07-01 11:00:00,10.67,39.0,17.67,39.20,32.33,7.07,...,14.50,1.00,4.63,33.43,71.67,2.30,226.33,123.67,NaN,-0.1
2016-07-01 11:00:00,NaT,NaT,NaT,2016-07-01 12:00:00,2.00,39.0,20.50,41.90,35.80,7.40,...,15.00,0.70,4.50,33.70,70.00,2.50,223.00,186.00,NaN,-0.1
2016-07-01 12:00:00,NaT,NaT,NaT,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,NaT,NaT,NaT,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,NaT,NaT,NaT,2016-07-01 15:00:00,20.50,50.0,15.40,43.60,32.78,6.35,...,10.50,0.60,4.50,33.57,63.50,1.88,223.00,240.50,NaN,-0.1
2016-07-01 15:00:00,NaT,NaT,NaT,2016-07-01 16:00:00,15.25,59.5,24.30,45.12,40.12,6.65,...,6.60,0.77,5.33,33.55,63.75,1.40,213.25,152.25,NaN,-0.1
2016-07-01 16:00:00,NaT,NaT,NaT,2016-07-01 17:00:00,11.67,60.0,26.73,49.10,43.80,6.93,...,17.43,0.80,6.47,33.57,64.00,1.50,208.67,92.67,NaN,-0.1

In [ ]:
shift_cleaned = shifting.drop(columns=['To Date'])
shift_cleaned.shift(periods=3,fill_value=0).head(7)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 11:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 12:00:00,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00,0.0,0.0,...,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.00
2016-07-01 13:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.6,0.48,14.5,1.0,...,33.43,71.67,2.3,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 14:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,0.7,...,33.70,70.00,2.5,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 16:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
shift_cleaned.shift(periods=3,fill_value=0,axis=1).head(7)

,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,0.0,0.0,0.0,10.67,39.0,17.67,39.20,32.33,7.07,6.60,...,14.50,1.00,4.63,33.43,71.67,2.30,226.33,123.67,NaN,-0.1
2016-07-01 11:00:00,0.0,0.0,0.0,2.00,39.0,20.50,41.90,35.80,7.40,NaN,...,15.00,0.70,4.50,33.70,70.00,2.50,223.00,186.00,NaN,-0.1
2016-07-01 12:00:00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,0.0,0.0,0.0,20.50,50.0,15.40,43.60,32.78,6.35,6.38,...,10.50,0.60,4.50,33.57,63.50,1.88,223.00,240.50,NaN,-0.1
2016-07-01 15:00:00,0.0,0.0,0.0,15.25,59.5,24.30,45.12,40.12,6.65,6.53,...,6.60,0.77,5.33,33.55,63.75,1.40,213.25,152.25,NaN,-0.1
2016-07-01 16:00:00,0.0,0.0,0.0,11.67,60.0,26.73,49.10,43.80,6.93,5.70,...,17.43,0.80,6.47,33.57,64.00,1.50,208.67,92.67,NaN,-0.1

# HANDLING MISSING DATA

In [ ]:
miss = pd.read_csv('/content/Air Quality.csv',index_col=0,parse_dates=['To Date'])
miss.head()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.0,17.67,39.2,32.33,7.07,6.60,0.48,14.5,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.1,0.1,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.0,20.50,41.9,35.80,7.40,NaN,0.49,15.0,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.1,0.1,0.0,NaN
2016-07-01 12:00:00,2016-07-01 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 13:00:00,2016-07-01 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.0,15.40,43.6,32.78,6.35,6.38,0.47,10.5,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.1,0.1,0.0,NaN

# isnull

In [ ]:
miss.isnull().sum()

To Date                0
PM2.5 (ug/m3)       4827
PM10 (ug/m3)        4700
NO (ug/m3)          3997
NO2 (ug/m3)         4050
NOx (ppb)           3835
NH3 (ug/m3)         5586
SO2 (ug/m3)         4865
CO (mg/m3)          4477
Ozone (ug/m3)       4583
Benzene (ug/m3)     3937
Toluene (ug/m3)     3937
Temp (degree C)     4037
RH (%)              3869
WS (m/s)            3851
WD (deg)            4494
SR (W/mt2)          4561
BP (mmHg)          57949
VWS (m/s)           3809
Xylene (ug/m3)      3950
RF (mm)             3865
AT (degree C)       4063
dtype: int64

# BFill

In [ ]:
miss.bfill()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,...,33.43,71.67,2.30,226.33,123.67,925.25,-0.10,0.10,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.38,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,925.25,-0.10,0.10,0.0,25.60
2016-07-01 12:00:00,2016-07-01 13:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
2016-07-01 13:00:00,2016-07-01 14:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,925.25,-0.10,0.10,0.0,25.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 19:00:00,2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,...,30.57,72.75,0.45,310.00,10.75,NaN,-0.20,0.85,0.0,25.23
2023-03-31 20:00:00,2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,...,30.65,78.50,0.35,37.00,11.00,NaN,-0.20,1.05,0.0,24.62
2023-03-31 21:00:00,2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,...,30.68,82.50,0.35,37.00,11.00,NaN,-0.20,0.73,0.0,24.23
2023-03-31 22:00:00,2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,...,30.60,86.00,0.30,NaN,11.00,NaN,-0.15,0.88,0.0,23.82
2023-03-31 23:00:00,2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,...,30.67,87.00,0.33,NaN,11.00,NaN,-0.13,0.83,0.0,23.50

# FFill

In [ ]:
miss.ffill()

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,...,33.43,71.67,2.30,226.33,123.67,NaN,-0.10,0.10,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 12:00:00,2016-07-01 13:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 13:00:00,2016-07-01 14:00:00,2.00,39.00,20.50,41.90,35.80,7.40,6.60,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,NaN,-0.10,0.10,0.0,23.05
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,NaN,-0.10,0.10,0.0,23.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 19:00:00,2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,...,30.57,72.75,0.45,310.00,10.75,749.0,-0.20,0.85,0.0,25.23
2023-03-31 20:00:00,2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,...,30.65,78.50,0.35,310.00,11.00,749.0,-0.20,1.05,0.0,24.62
2023-03-31 21:00:00,2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,...,30.68,82.50,0.35,37.00,11.00,749.0,-0.20,0.73,0.0,24.23
2023-03-31 22:00:00,2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,...,30.60,86.00,0.30,37.00,11.00,749.0,-0.15,0.88,0.0,23.82
2023-03-31 23:00:00,2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,...,30.67,87.00,0.33,37.00,11.00,749.0,-0.13,0.83,0.0,23.50

# FillNA

In [ ]:
miss.fillna(10)

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.67,39.00,17.67,39.20,32.33,7.07,6.60,0.48,14.50,...,33.43,71.67,2.30,226.33,123.67,10.0,-0.10,0.10,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.00,39.00,20.50,41.90,35.80,7.40,10.00,0.49,15.00,...,33.70,70.00,2.50,223.00,186.00,10.0,-0.10,0.10,0.0,10.00
2016-07-01 12:00:00,2016-07-01 13:00:00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,...,10.00,10.00,10.00,10.00,10.00,10.0,10.00,10.00,10.0,10.00
2016-07-01 13:00:00,2016-07-01 14:00:00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,...,10.00,10.00,10.00,10.00,10.00,10.0,10.00,10.00,10.0,10.00
2016-07-01 14:00:00,2016-07-01 15:00:00,20.50,50.00,15.40,43.60,32.78,6.35,6.38,0.47,10.50,...,33.57,63.50,1.88,223.00,240.50,10.0,-0.10,0.10,0.0,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 19:00:00,2023-03-31 20:00:00,53.00,70.25,11.03,61.15,41.52,8.30,3.68,1.16,12.30,...,30.57,72.75,0.45,310.00,10.75,10.0,-0.20,0.85,0.0,25.23
2023-03-31 20:00:00,2023-03-31 21:00:00,58.50,88.50,9.22,52.23,35.27,7.45,3.02,1.07,11.17,...,30.65,78.50,0.35,10.00,11.00,10.0,-0.20,1.05,0.0,24.62
2023-03-31 21:00:00,2023-03-31 22:00:00,44.25,80.50,3.40,34.95,21.35,7.25,1.62,0.85,10.60,...,30.68,82.50,0.35,37.00,11.00,10.0,-0.20,0.73,0.0,24.23
2023-03-31 22:00:00,2023-03-31 23:00:00,31.25,59.00,3.45,27.48,17.40,7.50,1.82,0.83,9.00,...,30.60,86.00,0.30,10.00,11.00,10.0,-0.15,0.88,0.0,23.82
2023-03-31 23:00:00,2023-04-01 00:00:00,26.00,53.00,3.33,24.07,15.50,7.70,1.83,0.81,8.37,...,30.67,87.00,0.33,10.00,11.00,10.0,-0.13,0.83,0.0,23.50

# Interpolate

In [ ]:
miss.interpolate(method='linear',limit_direction='forward')

,To Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),...,Temp (degree C),RH (%),WS (m/s),WD (deg),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C)
From Date,,,,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,2016-07-01 11:00:00,10.670000,39.000000,17.67,39.200000,32.330000,7.07,6.600,0.480000,14.50,...,33.430000,71.670000,2.300000,226.33,123.670000,NaN,-0.10,0.10,0.0,23.05
2016-07-01 11:00:00,2016-07-01 12:00:00,2.000000,39.000000,20.50,41.900000,35.800000,7.40,6.545,0.490000,15.00,...,33.700000,70.000000,2.500000,223.00,186.000000,NaN,-0.10,0.10,0.0,23.56
2016-07-01 12:00:00,2016-07-01 13:00:00,8.166667,42.666667,18.80,42.466667,34.793333,7.05,6.490,0.483333,13.50,...,33.656667,67.833333,2.293333,223.00,204.166667,NaN,-0.10,0.10,0.0,24.07
2016-07-01 13:00:00,2016-07-01 14:00:00,14.333333,46.333333,17.10,43.033333,33.786667,6.70,6.435,0.476667,12.00,...,33.613333,65.666667,2.086667,223.00,222.333333,NaN,-0.10,0.10,0.0,24.58
2016-07-01 14:00:00,2016-07-01 15:00:00,20.500000,50.000000,15.40,43.600000,32.780000,6.35,6.380,0.470000,10.50,...,33.570000,63.500000,1.880000,223.00,240.500000,NaN,-0.10,0.10,0.0,25.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31 19:00:00,2023-03-31 20:00:00,53.000000,70.250000,11.03,61.150000,41.520000,8.30,3.680,1.160000,12.30,...,30.570000,72.750000,0.450000,310.00,10.750000,749.0,-0.20,0.85,0.0,25.23
2023-03-31 20:00:00,2023-03-31 21:00:00,58.500000,88.500000,9.22,52.230000,35.270000,7.45,3.020,1.070000,11.17,...,30.650000,78.500000,0.350000,173.50,11.000000,749.0,-0.20,1.05,0.0,24.62
2023-03-31 21:00:00,2023-03-31 22:00:00,44.250000,80.500000,3.40,34.950000,21.350000,7.25,1.620,0.850000,10.60,...,30.680000,82.500000,0.350000,37.00,11.000000,749.0,-0.20,0.73,0.0,24.23
2023-03-31 22:00:00,2023-03-31 23:00:00,31.250000,59.000000,3.45,27.480000,17.400000,7.50,1.820,0.830000,9.00,...,30.600000,86.000000,0.300000,37.00,11.000000,749.0,-0.15,0.88,0.0,23.82
2023-03-31 23:00:00,2023-04-01 00:00:00,26.000000,53.000000,3.33,24.070000,15.500000,7.70,1.830,0.810000,8.37,...,30.670000,87.000000,0.330000,37.00,11.000000,749.0,-0.13,0.83,0.0,23.50

# **CONCLUSION**

In this experiment we learn how to use SQL queries in python using pandas. Also we learn how to do preprocessing and many other functions like windowing, shifting etc